apiVersion: v1
kind: Service
metadata:
  name: studiodrop-service
  namespace: studiodrop
spec:
  selector:
    app: studiodrop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
